substitutions:
  name: esp32c6-seeed-pytes
  board: seeed_xiao_esp32c6

esphome:
  name: ${name}
  friendly_name: ESP32c6-seeed-Pytes

esp32:
  board: ${board}
  variant: esp32c6
  framework:
    type: esp-idf

external_components:
  - source: github://oxynatOr/esphome-pytes_e_box@main
    components: [ pytes_e_box ]
    refresh: 5s

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32C6-Seeed-Pytes"
    password: !secret fallback_password

captive_portal:

uart:
#stack 1 rs232 console port
  - id: uart01
    tx_pin: GPIO16
    rx_pin: GPIO17
    baud_rate: 115200
    rx_buffer_size: 1024
    parity: NONE
    stop_bits: 1
    
#stack 2 rs232 console port  
  - id: uart02
    tx_pin: GPIO21
    rx_pin: GPIO20
    baud_rate: 115200
    rx_buffer_size: 1024
    parity: NONE 
    stop_bits: 1

# mkdir packages inside the same directory as where you find all of esphome .yaml files
# copy pytesebox-monitor.yaml and put inside your newly created packages directory
# for exampl my esphome is a docker container inside my opt directory 
# /opt/esphome/packages/pytesebox-monitor.yaml
packages:
  # First E-Box Stack (uart01, pvbatt01) - batteries 1-5
  pytes_ebox_1: !include 
    file: packages/pytesebox-monitor.yaml
    vars:
      pytes_e_box_id: pvbatt01
      battery_num: 1
      cell_prefix: "Cell"
      battery_prefix: "Battery"
  pytes_ebox_2: !include 
    file: packages/pytesebox-monitor.yaml
    vars:
      pytes_e_box_id: pvbatt01
      battery_num: 2
      cell_prefix: "Cell"
      battery_prefix: "Battery"
  pytes_ebox_3: !include 
    file: packages/pytesebox-monitor.yaml
    vars:
      pytes_e_box_id: pvbatt01
      battery_num: 3
      cell_prefix: "Cell"
      battery_prefix: "Battery"
  pytes_ebox_4: !include 
    file: packages/pytesebox-monitor.yaml
    vars:
      pytes_e_box_id: pvbatt01
      battery_num: 4
      cell_prefix: "Cell"
      battery_prefix: "Battery"
  pytes_ebox_5: !include 
    file: packages/pytesebox-monitor.yaml
    vars:
      pytes_e_box_id: pvbatt01
      battery_num: 5
      cell_prefix: "Cell"
      battery_prefix: "Battery"
  
  # Second E-Box Stack (uart02, pvbatt2) - batteries 1-5
  pytes_ebox_6: !include 
    file: packages/pytesebox-monitor.yaml
    vars:
      pytes_e_box_id: pvbatt02 
      battery_num: 1
      cell_prefix: "Cell"
      battery_prefix: "Battery"
  pytes_ebox_7: !include 
    file: packages/pytesebox-monitor.yaml
    vars:
      pytes_e_box_id: pvbatt02 
      battery_num: 2
      cell_prefix: "Cell"
      battery_prefix: "Battery"
  pytes_ebox_8: !include 
    file: packages/pytesebox-monitor.yaml
    vars:
      pytes_e_box_id: pvbatt02 
      battery_num: 3
      cell_prefix: "Cell"
      battery_prefix: "Battery"
  pytes_ebox_9: !include 
    file: packages/pytesebox-monitor.yaml
    vars:
      pytes_e_box_id: pvbatt02 
      battery_num: 4
      cell_prefix: "Cell"
      battery_prefix: "Battery"
  pytes_ebox_10: !include 
    file: packages/pytesebox-monitor.yaml
    vars:
      pytes_e_box_id: pvbatt02 
      battery_num: 5
      cell_prefix: "Cell"
      battery_prefix: "Battery"

pytes_e_box:
  - id: pvbatt01
    uart_id: uart01
    update_interval: 30s
    batteries: 5
    poll_timeout: 4s 
    command_idle_time: 150ms
  
  - id: pvbatt02
    uart_id: uart02
    update_interval: 30s
    batteries: 5
    poll_timeout: 4s 
    command_idle_time: 150ms
